#!/usr/bin/env python3
"""markdown -> Typst report PDF, using this kit's theme.

Pipeline:
    markdown --(pandoc -t typst)--> body.typ --(typst compile)--> PDF
A small wrapper file is generated that imports theme.typ, renders a cover
and the running header/footer, then `#include`s the converted body.

Requires: python3 (stdlib only), pandoc, typst.

Usage:
    python scripts/md_to_typst.py input.md output.pdf \
        --title "Doc title" --date 2026-01-01 --footer "Running footer" \
        [--typst /path/to/typst] [--pandoc /path/to/pandoc] [--workdir DIR]

Tool resolution order: --typst/--pandoc flag, then $TYPST_PATH/$PANDOC_PATH,
then PATH. The Typst universe packages (codly, fletcher) are fetched on the
first run, so set HTTPS_PROXY if you are behind a proxy.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys

WRAPPER = """// Generated by scripts/md_to_typst.py - do not edit by hand.
#import "{theme}": *

#report(
  doc-title: {title},
  doc-date: {date},
  doc-footer: {footer},
  numbered: {numbered},
)[
  #cover(
    kicker: {kicker},
    title: {title},
    sub: {date},
    core-label: [Positioning],
    core: {core},
    meta: {meta},
  )

  #pagebreak()
  #include "{body}"
]
"""


def parse_frontmatter(text):
    """Parse a leading `---` frontmatter block of `key: value` pairs."""
    meta, body_start = {}, 0
    lines = text.split("\n")
    if lines and lines[0].strip() == "---":
        i = 1
        while i < len(lines) and lines[i].strip() != "---":
            m = re.match(r"^([\w\-]+)\s*[=:]\s*(.*)$", lines[i].strip())
            if m:
                meta[m.group(1)] = m.group(2).strip().strip('"').strip("'")
            i += 1
        body_start = i + 1
    return meta, body_start


def fix_body(text):
    """Work around pandoc's typst math writer gluing tokens to neighbours.

    - `^top` followed by a letter becomes the variable `^topV` -> insert a space
    - `divides` glued to a prefix becomes `_Rdivides` -> insert a space
    - `upright(` glued to an identifier -> insert a space
    All three targets are valid Typst symbols, so a space restores intent.
    """
    text = re.sub(r"(\^top)([A-Za-z0-9])", r"\1 \2", text)
    text = re.sub(r"([A-Za-z0-9_)\]}])(divides)", r"\1 \2", text)
    text = re.sub(r"([A-Za-z0-9_])(upright\()", r"\1 \2", text)
    return text


def resolve(explicit, env_var, name):
    cand = explicit or os.environ.get(env_var) or shutil.which(name)
    if not cand or not os.path.exists(cand):
        sys.exit(f"error: {name} not found. Pass --{name} or set ${env_var}, "
                 f"or put it on PATH.")
    return cand


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("md", help="input markdown file")
    ap.add_argument("out_pdf", help="output PDF path")
    ap.add_argument("--title", default=None, help="doc title (default: frontmatter title or first H1)")
    ap.add_argument("--date", default=None, help="doc date (default: frontmatter created)")
    ap.add_argument("--footer", default=None, help="running footer label (default: title)")
    ap.add_argument("--kicker", default="", help="cover kicker line")
    ap.add_argument("--core", default="", help="cover positioning paragraph")
    ap.add_argument("--meta", default="", help="cover meta line")
    ap.add_argument("--numbered", action="store_true", help="number level-1 headings")
    ap.add_argument("--workdir", default=None, help="scratch dir for generated .typ (default: <repo>/.build/<stem>)")
    ap.add_argument("--typst", default=None, help="path to the typst binary")
    ap.add_argument("--pandoc", default=None, help="path to the pandoc binary")
    a = ap.parse_args()

    pandoc = resolve(a.pandoc, "PANDOC_PATH", "pandoc")
    typst = resolve(a.typst, "TYPST_PATH", "typst")

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_pdf = os.path.abspath(a.out_pdf)
    stem = os.path.splitext(os.path.basename(a.md))[0]
    work = os.path.abspath(a.workdir or os.path.join(repo, ".build", stem))
    os.makedirs(work, exist_ok=True)

    with open(a.md, encoding="utf-8") as f:
        raw = f.read()
    meta, body_start = parse_frontmatter(raw)
    lines = raw.split("\n")
    first_h1 = ""
    for ln in lines[body_start:]:
        if ln.startswith("# "):
            first_h1 = ln[2:].strip()
            break

    title = a.title or meta.get("title") or first_h1 or os.path.splitext(os.path.basename(a.md))[0]
    date = a.date or meta.get("created", "").replace("/", "-")
    footer = a.footer or meta.get("title") or title
    kicker = a.kicker or meta.get("source", "")

    # Strip frontmatter before pandoc, otherwise it renders as a metadata table.
    body_md = os.path.join(work, "md_body.md")
    with open(body_md, "w", encoding="utf-8") as f:
        f.write("\n".join(lines[body_start:]).lstrip("\n"))

    body_typ = os.path.join(work, "body.typ")
    r = subprocess.run([pandoc, body_md, "-t", "typst", "-o", body_typ],
                       capture_output=True, text=True, encoding="utf-8")
    if r.returncode != 0:
        sys.exit("PANDOC FAIL:\n" + (r.stderr or "")[-2000:])
    with open(body_typ, encoding="utf-8") as f:
        converted = f.read()
    with open(body_typ, "w", encoding="utf-8") as f:
        f.write(fix_body(converted))

    import json
    S = lambda v: json.dumps(str(v), ensure_ascii=False)

    def rel(path):
        """Path relative to the workdir, with a cross-drive fallback."""
        try:
            return os.path.relpath(path, work).replace("\\", "/")
        except ValueError:  # different drive on Windows: relpath is impossible
            return os.path.abspath(path).replace("\\", "/")

    wrapper = os.path.join(work, "wrapper.typ")
    with open(wrapper, "w", encoding="utf-8") as f:
        f.write(WRAPPER.format(
            theme=rel(os.path.join(repo, "theme.typ")), body=rel(body_typ),
            title=S(title), date=S(date), footer=S(footer), kicker=S(kicker),
            core=S(a.core), meta=S(a.meta),
            numbered="true" if a.numbered else "false",
        ))

    # --root is the repo so that `theme.typ` resolves outside the workdir.
    r = subprocess.run([typst, "compile", "--root", repo, wrapper, out_pdf],
                       capture_output=True, text=True, encoding="utf-8")
    if r.returncode != 0:
        sys.exit("TYPST FAIL:\n" + (r.stderr or "")[-3000:])
    print(f"OK: {out_pdf} ({os.path.getsize(out_pdf)} bytes)")
    if r.stderr.strip():
        print(r.stderr.strip(), file=sys.stderr)


if __name__ == "__main__":
    main()
