// ============================================================
// Book-style example — same theme, book-adapted settings.
// The long body is normally generated by scripts/md_to_typst.py
// (markdown -> pandoc -> body.typ); body.typ here is a placeholder.
//
// Compile:
//   typst compile --root .. examples/book/book.typ
// ============================================================

#import "../../theme.typ": *

#report(
  doc-title: [Generic book title],
  doc-date: [2026-01-01],
  doc-footer: [Generic book title],
  numbered: false,
  leading: 0.55em,
  quote-style: "green",
)[

  // ============ Cover ============
  #cover(
    kicker: [Section title · placeholder label],
    title: [Generic book title],
    sub: [
      Placeholder subtitle line one#linebreak()
      Placeholder subtitle line two#linebreak()
      Placeholder subtitle line three
    ],
    core-label: [What this book is],
    core: [
      Lorem-like placeholder Chinese text 占位：这里说明本书的定位、覆盖范围与目标读者。
    ],
    meta: [
      your-org · your-team#linebreak()
      2026-01-01 · placeholder meta line
    ],
    decoration: "disc",
  )

  // ============ Body ============
  #pagebreak()
  #include "body.typ"
]
